### ISSUE TITLE
Assets.car Rendition edit problem

### ISSUE THREAD

**Issue by sourcelocation** [NSAntoine/PrivateKits#1]
Hi, first of all, amazing project, I wouldn't be able to build TrollTools without it, huge props. 

I have encountered an issue where some icon files can't be edited in Santander and in my app. 
![IMG_3C9E4F2E96AE-1](https://user-images.githubusercontent.com/52459150/198313100-10f9ed6e-720c-4c6f-bea7-fac3d9811607.jpeg)
Here's the error from santander, and here's an error on my end:
<img width="278" alt="Screenshot 2022-10-27 at 15 25 52" src="https://user-images.githubusercontent.com/52459150/198313473-b5934840-1e2c-4bf6-9bff-43716e7a3e1c.png">
(It's an error which appears after .editItem is invoked)

Do you have any ideas how to fix this bug?

**Comment by sourcelocation** [comment]
An easy way to reproduce this issue is to try and edit icon of any TrollStore sideloaded app, I used uYouPlus

**Comment by NSAntoine** [comment]
You may need a root helper of some sort to invoke the edit function and I don’t even know if that too would work, CoreUI is really weird with its init to CUIMutableCommonAssetStorage which is why this even happens

**Comment by sourcelocation** [comment]
I see. My solution was to move Assets.car to temp location, set permissions, edit it and then move it back. That works for most icons, but doesn't for some. Maybe we can hop into a vc?
