### ISSUE TITLE
Samra cannot compile because Private frameworks tbd platform is set to ios

### ISSUE THREAD

**Issue by Mx-Iris** [NSAntoine/PrivateKits#3]
Considering upgrading tbd v4 or setting it to zippera?

**Comment by NSAntoine** [comment]
Do you have any example of the tbd v4 format?

**Comment by Mx-Iris** [comment]
macOS PrivateFrameworks tbd can be found here 
`/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/PrivateFrameworks`
for example:
`/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/PrivateFrameworks/CoreUI.framework/CoreUI.tbd`

**Comment by Mx-Iris** [comment]
The version of tbd found inside the Xcode 15 sdk is v4

**Comment by Mx-Iris** [comment]
You can also generate a specific version of tbd from this library
[inoahdev/tbd](https://github.com/inoahdev/tbd)

**Comment by NSAntoine** [comment]
Should work now, try re-compiling w the latest PrivateKits

**Comment by Mx-Iris** [comment]
Thanks. It's working now.
